<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CartService.Domain\CartService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="13.0.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.16" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\AddToCart\" />
    </ItemGroup>

</Project>
